language: python

# Run jobs on container-based infrastructure, can be overridden per job

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env: PYTHON_VER=3.6
    - os: osx
      language: generic
      env: PYTHON_VER=3.7


    - os: linux
      language: generic  # No need to set Python version since its conda
      env: PYTHON_VER=3.6
    - os: linux
      language: generic
      env: PYTHON_VER=3.7

addons:
  chrome: beta

# branches to build
branches:
    only:
    - master
    - consume-api


before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CHROME_BETA=$(which google-chrome-beta); fi
    # Create test environment for package
  - python devtools/scripts/create_conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/test_env.yaml
    # Activate the test environment
  - conda activate test
  - conda list
  - cd app
  - cd static
  - npm install
  - cd ../../
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version; fi
    # Build and install package
  - python setup.py develop --no-deps


script:
   - pytest -v --cov=app app/tests/

notifications:
    email: false

after_success:
  - codecov